### ISSUE TITLE
 [FEATURE] Add support for `Llama-3-1-405B-Instruct`

### ISSUE THREAD

**Issue by guibranco** [guibranco/dotnet-aicommitmessage#154]
I want to be able to use the **Llama-3-1-405B-Instruct** language model in the tool `dotnet-aicommitmessage`.  
To achieve this, I need to follow the instructions provided on [this page](https://github.com/marketplace/models/azureml-meta/Llama-3-3-70B-Instruct/playground) under the "Get API Key" button.  

#### Steps to Implement  
1. Install the **Azure AI Inference SDK**.  
2. Generate and configure a GitHub token for Azure AI access.  
3. Update the tool to support **Llama-3-1-405B-Instruct** as an alternative model.  
4. Add documentation explaining how to configure and use this model instead of the default OpenAI model.  
5. Add tests to validate the integration and ensure proper behavior when using the new model.  

---

### Acceptance Criteria  
- [ ] Install the Azure AI inference SDK in the project.  
- [ ] Add support for the Llama-3-1-405B-Instruct LLM.  
- [ ] Generate and use the required GitHub token for accessing Azure AI.  
- [ ] Update the documentation to include configuration steps for Llama-3-1-405B-Instruct.  
- [ ] Include unit tests and integration tests for the new functionality.  
- [ ] Ensure the new model works seamlessly alongside the default OpenAI model.  

#### Additional Context  
- Reference link: [Llama-3-3-70B-Instruct on GitHub](https://github.com/marketplace/models/azureml-meta/Llama-3-3-70B-Instruct/playground)

**Comment by RyanFloresTT** [comment]
Hi @guibranco 

I’m new to open-source. I came across your project and found it really interesting!
If it’s okay, I'd like to work on this issue :)

Thanks

**Comment by RyanFloresTT** [comment]
Hello,

I’m implementing the ability to swap to Llama-3-1-405B-Instruct. I’m assuming that users would set their settings (API key, URL, model) once per model, and those settings would persist, allowing them to swap between models without re-declaring everything. For example:

```bash
# Set Llama settings
dotnet-aicommitmessage set-settings -m llama-3-1-405B-Instruct -k {llama-api-key} -u {llama-api-url}

# Use Llama
git commit -m "."

# Set GPT settings
dotnet-aicommitmessage set-settings -m gpt-4o-mini -k {gpt-api-key} -u {gpt-api-url}

# Use GPT
git commit -m "."

# Swap back to Llama without re-declaring
dotnet-aicommitmessage set-settings -m llama-3-1-405B-Instruct
git commit -m "."

# Swap back to GPT without re-declaring
dotnet-aicommitmessage set-settings -m gpt-4o-mini
git commit -m "."
```

Does this align with your expectations? I just want to confirm this flow before proceeding further.

Thanks!

**Comment by guibranco** [comment]
Yeah, this feature is still being deployed, but your approach is correct!
